version: 2.1

orbs:
     python: circleci/python@0.3.2

jobs:
     build-and-test:
      executor: python/default
      steps:
        - checkout
        - python/install-deps
        - run: python testScript.py
        - run: behave ./features/navBar.feature
        # - pip install beahve
        # - behave ./features/navBar.feature
        # - behave ./features/Homepage.feature

commands:
    build_source:
      description: 'runs feature file'
      steps:
        - behave: ./features/navBar.feature



workflows: 
   main:
     jobs:
       - build-and-test