version: 2.1

orbs:
     browser-tools: circleci/browser-tools@1.1
     python: circleci/python@0.3.2

jobs:
     build-and-test:
      docker:
        - image: cimg/python:3.7-browsers
     # executor: python/default
      steps: 
        - browser-tools/install-browser-tools
        - checkout
        - python/install-deps
        - run: python --version
        - run: google-chrome --version
        - run: chromedriver --version
        - run: python testScript.py
        - run: behave ./features/navBar.feature
        
        # - pip install beahve
        # - behave ./features/navBar.feature
        # - behave ./features/Homepage.feature

commands:
    build_source:
      description: 'runs feature file'
      steps:
        - behave: ./features/navBar.feature



workflows: 
   main:
     jobs:
       - build-and-test